### ISSUE TITLE
Error endpoint

### ISSUE THREAD

**Issue by bonnebulle** [webhainaut/ovh-dyndns-docker#3]
The log says :
```exec /srv/dyndns/entrypoint.sh: exec format error```

my credentials are good when I do :
```curl -u "userdomain.tld-dnsuser:PASSWORD" https://dns.eu.ovhapis.com/nic/update\?system\=dyndns\&hostname=userdomain.tld&myip=$IPNOW```

**Comment by webhainaut** [comment]
Sorry, I don't support this project.

But to not let you without anything, first, in this project, I use "https://www.ovh.com/nic/update" and not "https://dns.eu.ovhapis.com/nic/update". I don't know if this change something.

How do you use the project ?

**Comment by bonnebulle** [comment]
Thanks for the non EU link
I give a try with it to check my credentials...
all was ok... but not working in my cli/bash environment...
so, I removed some characters from my password... 
and now, all working ok
Thanks
